### ISSUE TITLE
`register_shutdown_function` cause socket leak.

### ISSUE THREAD

**Issue by kafkiansky** [VKCOM/statshouse-php#5]
As documentation [says](https://www.php.net/manual/en/function.register-shutdown-function.php), the functions registered through the `register_shutdown_function` will execute after script is finished. In modern applications, where we use inversion of control, objects are die and are created all the time. In this case, the client will not close the socket until the worker is reloaded (I'm talking about applications running in daemon mode), that cause socket leak and problem with open the new one. Perhaps we can use a destructor for this, or give another way to explicitly close the socket?

**Comment by flyingmutant** [comment]
Closing and re-opening sockets all the time sounds like a bad idea. Wouldn't the proper solution be to teach your dependency injection framework to re-use the same StatsHouse instance through the entire application lifetime?

**Comment by kafkiansky** [comment]
> Closing and re-opening sockets all the time sounds like a bad idea. Wouldn't the proper solution be to teach your dependency injection framework to re-use the same StatsHouse instance through the entire application lifetime?

We don't intend to open and close sockets every time, but would like to manage ourselves when resources close, even if the application continues to run. This is not possible with shutdown functions, because you have to stop the script.
